/* Generated by re2c 0.13.5 on Thu Apr 26 14:27:02 2012 */
#line 1 "lib/Nana/toke.re"
/* vim: set filetype=cpp: */
#include<stdio.h>

/**
 * Take a token from string.
 *
 * @args src: source string.
 * @args len: length for 'src'.
 * @args output *used: used chars in src
 * @args output *found_end: make true if found __END__
 * @args output *lineno_inc: incremented line numbers.
 * @return int token id.
 */
int token_op(char *src, size_t len, int *used, int *found_end, int *lineno_inc) {
#define OP(type) do { *used+=(cursor-orig); return type; } while (0)
    *used = skip_ws(src, len, found_end, lineno_inc);
    if (*found_end) {
        return TOKEN_EOF;
    }
    if (*used == len) {
        return TOKEN_EOF;
    }
    char *cursor = src+*used;
    char *orig = cursor;
    char *marker = cursor;

    #line 38 "lib/Nana/toke.re"


    
#line 34 "lib/Nana/toke.c"
	{
		char yych;

		yych = (char)*cursor;
		switch (yych) {
		case '!':	goto yy16;
		case '"':	goto yy40;
		case '$':	goto yy34;
		case '%':	goto yy12;
		case '&':	goto yy26;
		case '\'':	goto yy42;
		case '(':	goto yy6;
		case '*':	goto yy35;
		case '+':	goto yy2;
		case ',':	goto yy14;
		case '-':	goto yy46;
		case '.':	goto yy22;
		case '/':	goto yy10;
		case '<':	goto yy8;
		case '=':	goto yy18;
		case '>':	goto yy28;
		case '[':	goto yy44;
		case '\\':	goto yy30;
		case '^':	goto yy20;
		case 'b':	goto yy4;
		case 'q':	goto yy39;
		case '{':	goto yy37;
		case '|':	goto yy24;
		case '~':	goto yy32;
		default:	goto yy48;
		}
yy2:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '+':	goto yy129;
		case '=':	goto yy127;
		default:	goto yy3;
		}
yy3:
#line 43 "lib/Nana/toke.re"
		{ OP(TOKEN_PLUS);  }
#line 76 "lib/Nana/toke.c"
yy4:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '"':	goto yy123;
		case '\'':	goto yy125;
		default:	goto yy5;
		}
yy5:
#line 108 "lib/Nana/toke.re"
		{ return TOKEN_EOF; }
#line 87 "lib/Nana/toke.c"
yy6:
		++cursor;
#line 46 "lib/Nana/toke.re"
		{ OP(TOKEN_LPAREN);  }
#line 92 "lib/Nana/toke.c"
yy8:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '<':	goto yy115;
		case '=':	goto yy113;
		default:	goto yy9;
		}
yy9:
#line 77 "lib/Nana/toke.re"
		{ OP(TOKEN_GT); }
#line 103 "lib/Nana/toke.c"
yy10:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy111;
		default:	goto yy11;
		}
yy11:
#line 49 "lib/Nana/toke.re"
		{ OP(TOKEN_DIV); }
#line 113 "lib/Nana/toke.c"
yy12:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy109;
		default:	goto yy13;
		}
yy13:
#line 51 "lib/Nana/toke.re"
		{ OP(TOKEN_MOD); }
#line 123 "lib/Nana/toke.c"
yy14:
		++cursor;
#line 52 "lib/Nana/toke.re"
		{ OP(TOKEN_COMMA); }
#line 128 "lib/Nana/toke.c"
yy16:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy107;
		case '~':	goto yy105;
		default:	goto yy17;
		}
yy17:
#line 55 "lib/Nana/toke.re"
		{ OP(TOKEN_NOT); }
#line 139 "lib/Nana/toke.c"
yy18:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy103;
		case '>':	goto yy101;
		case '~':	goto yy99;
		default:	goto yy19;
		}
yy19:
#line 59 "lib/Nana/toke.re"
		{ OP(TOKEN_ASSIGN); }
#line 151 "lib/Nana/toke.c"
yy20:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy97;
		default:	goto yy21;
		}
yy21:
#line 61 "lib/Nana/toke.re"
		{ OP(TOKEN_XOR); }
#line 161 "lib/Nana/toke.c"
yy22:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '.':	goto yy93;
		default:	goto yy23;
		}
yy23:
#line 64 "lib/Nana/toke.re"
		{ OP(TOKEN_DOT); }
#line 171 "lib/Nana/toke.c"
yy24:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy87;
		case '|':	goto yy89;
		default:	goto yy25;
		}
yy25:
#line 68 "lib/Nana/toke.re"
		{ OP(TOKEN_OR); }
#line 182 "lib/Nana/toke.c"
yy26:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '&':	goto yy85;
		case '=':	goto yy83;
		default:	goto yy27;
		}
yy27:
#line 71 "lib/Nana/toke.re"
		{ OP(TOKEN_AND); }
#line 193 "lib/Nana/toke.c"
yy28:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy77;
		case '>':	goto yy79;
		default:	goto yy29;
		}
yy29:
#line 81 "lib/Nana/toke.re"
		{ OP(TOKEN_LT); }
#line 204 "lib/Nana/toke.c"
yy30:
		++cursor;
#line 82 "lib/Nana/toke.re"
		{ OP(TOKEN_REF); }
#line 209 "lib/Nana/toke.c"
yy32:
		++cursor;
#line 83 "lib/Nana/toke.re"
		{ OP(TOKEN_TILDE); }
#line 214 "lib/Nana/toke.c"
yy34:
		yych = (char)*++cursor;
		switch (yych) {
		case '{':	goto yy75;
		default:	goto yy5;
		}
yy35:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '*':	goto yy71;
		case '=':	goto yy69;
		default:	goto yy36;
		}
yy36:
#line 88 "lib/Nana/toke.re"
		{ OP(TOKEN_MUL); }
#line 231 "lib/Nana/toke.c"
yy37:
		++cursor;
#line 92 "lib/Nana/toke.re"
		{ OP(TOKEN_LBRACE); }
#line 236 "lib/Nana/toke.c"
yy39:
		yych = (char)*(marker = ++cursor);
		switch (yych) {
		case '!':
		case '"':
		case '\'':
		case '(':
		case '[':
		case '{':	goto yy57;
		case 'q':	goto yy62;
		case 'r':	goto yy61;
		case 'w':	goto yy59;
		default:	goto yy5;
		}
yy40:
		++cursor;
#line 100 "lib/Nana/toke.re"
		{ OP(TOKEN_STRING_DQ); }
#line 255 "lib/Nana/toke.c"
yy42:
		++cursor;
#line 101 "lib/Nana/toke.re"
		{ OP(TOKEN_STRING_SQ); }
#line 260 "lib/Nana/toke.c"
yy44:
		++cursor;
#line 102 "lib/Nana/toke.re"
		{ OP(TOKEN_LBRACKET); }
#line 265 "lib/Nana/toke.c"
yy46:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '-':	goto yy53;
		case '=':	goto yy49;
		case '>':	goto yy51;
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy55;
		default:	goto yy47;
		}
yy47:
#line 107 "lib/Nana/toke.re"
		{ OP(TOKEN_MINUS); }
#line 303 "lib/Nana/toke.c"
yy48:
		yych = (char)*++cursor;
		goto yy5;
yy49:
		++cursor;
#line 106 "lib/Nana/toke.re"
		{ OP(TOKEN_MINUS_ASSIGN); }
#line 311 "lib/Nana/toke.c"
yy51:
		++cursor;
#line 105 "lib/Nana/toke.re"
		{ OP(TOKEN_LAMBDA); }
#line 316 "lib/Nana/toke.c"
yy53:
		++cursor;
#line 104 "lib/Nana/toke.re"
		{ OP(TOKEN_MINUSMINUS); }
#line 321 "lib/Nana/toke.c"
yy55:
		++cursor;
#line 103 "lib/Nana/toke.re"
		{ OP(TOKEN_FILETEST); }
#line 326 "lib/Nana/toke.c"
yy57:
		++cursor;
#line 99 "lib/Nana/toke.re"
		{ OP(TOKEN_STRING_Q_START); }
#line 331 "lib/Nana/toke.c"
yy59:
		yych = (char)*++cursor;
		switch (yych) {
		case '!':
		case '"':
		case '\'':
		case '(':
		case '[':
		case '{':	goto yy67;
		default:	goto yy60;
		}
yy60:
		cursor = marker;
		goto yy5;
yy61:
		yych = (char)*++cursor;
		switch (yych) {
		case '!':
		case '"':
		case '\'':
		case '(':
		case '[':
		case '{':	goto yy65;
		default:	goto yy60;
		}
yy62:
		yych = (char)*++cursor;
		switch (yych) {
		case '!':
		case '"':
		case '\'':
		case '(':
		case '[':
		case '{':	goto yy63;
		default:	goto yy60;
		}
yy63:
		++cursor;
#line 96 "lib/Nana/toke.re"
		{ OP(TOKEN_STRING_QQ_START); }
#line 372 "lib/Nana/toke.c"
yy65:
		++cursor;
#line 97 "lib/Nana/toke.re"
		{ OP(TOKEN_REGEXP_QR_START); }
#line 377 "lib/Nana/toke.c"
yy67:
		++cursor;
#line 98 "lib/Nana/toke.re"
		{ OP(TOKEN_QW_START); }
#line 382 "lib/Nana/toke.c"
yy69:
		++cursor;
#line 87 "lib/Nana/toke.re"
		{ OP(TOKEN_MUL_ASSIGN); }
#line 387 "lib/Nana/toke.c"
yy71:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy73;
		default:	goto yy72;
		}
yy72:
#line 86 "lib/Nana/toke.re"
		{ OP(TOKEN_POW); }
#line 397 "lib/Nana/toke.c"
yy73:
		++cursor;
#line 85 "lib/Nana/toke.re"
		{ OP(TOKEN_POW_ASSIGN); }
#line 402 "lib/Nana/toke.c"
yy75:
		++cursor;
#line 84 "lib/Nana/toke.re"
		{ OP(TOKEN_DEREF); }
#line 407 "lib/Nana/toke.c"
yy77:
		++cursor;
#line 80 "lib/Nana/toke.re"
		{ OP(TOKEN_LE); }
#line 412 "lib/Nana/toke.c"
yy79:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy81;
		default:	goto yy80;
		}
yy80:
#line 79 "lib/Nana/toke.re"
		{ OP(TOKEN_RSHIFT); }
#line 422 "lib/Nana/toke.c"
yy81:
		++cursor;
#line 78 "lib/Nana/toke.re"
		{ OP(TOKEN_RSHIFT_ASSIGN); }
#line 427 "lib/Nana/toke.c"
yy83:
		++cursor;
#line 70 "lib/Nana/toke.re"
		{ OP(TOKEN_AND_ASSIGN); }
#line 432 "lib/Nana/toke.c"
yy85:
		++cursor;
#line 69 "lib/Nana/toke.re"
		{ OP(TOKEN_ANDAND); }
#line 437 "lib/Nana/toke.c"
yy87:
		++cursor;
#line 67 "lib/Nana/toke.re"
		{ OP(TOKEN_OR_ASSIGN); }
#line 442 "lib/Nana/toke.c"
yy89:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy91;
		default:	goto yy90;
		}
yy90:
#line 66 "lib/Nana/toke.re"
		{ OP(TOKEN_OROR); }
#line 452 "lib/Nana/toke.c"
yy91:
		++cursor;
#line 65 "lib/Nana/toke.re"
		{ OP(TOKEN_OROR_ASSIGN); }
#line 457 "lib/Nana/toke.c"
yy93:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '.':	goto yy95;
		default:	goto yy94;
		}
yy94:
#line 63 "lib/Nana/toke.re"
		{ OP(TOKEN_DOTDOT); }
#line 467 "lib/Nana/toke.c"
yy95:
		++cursor;
#line 62 "lib/Nana/toke.re"
		{ OP(TOKEN_DOTDOTDOT); }
#line 472 "lib/Nana/toke.c"
yy97:
		++cursor;
#line 60 "lib/Nana/toke.re"
		{ OP(TOKEN_XOR_ASSIGN); }
#line 477 "lib/Nana/toke.c"
yy99:
		++cursor;
#line 58 "lib/Nana/toke.re"
		{ OP(TOKEN_REGEXP_MATCH); }
#line 482 "lib/Nana/toke.c"
yy101:
		++cursor;
#line 57 "lib/Nana/toke.re"
		{ OP(TOKEN_FAT_COMMA); }
#line 487 "lib/Nana/toke.c"
yy103:
		++cursor;
#line 56 "lib/Nana/toke.re"
		{ OP(TOKEN_EQUAL_EQUAL); }
#line 492 "lib/Nana/toke.c"
yy105:
		++cursor;
#line 54 "lib/Nana/toke.re"
		{ OP(TOKEN_REGEXP_NOT_MATCH); }
#line 497 "lib/Nana/toke.c"
yy107:
		++cursor;
#line 53 "lib/Nana/toke.re"
		{ OP(TOKEN_NOT_EQUAL); }
#line 502 "lib/Nana/toke.c"
yy109:
		++cursor;
#line 50 "lib/Nana/toke.re"
		{ OP(TOKEN_MOD_ASSIGN); }
#line 507 "lib/Nana/toke.c"
yy111:
		++cursor;
#line 48 "lib/Nana/toke.re"
		{ OP(TOKEN_DIV_ASSIGN); }
#line 512 "lib/Nana/toke.c"
yy113:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '>':	goto yy121;
		default:	goto yy114;
		}
yy114:
#line 76 "lib/Nana/toke.re"
		{ OP(TOKEN_GE); }
#line 522 "lib/Nana/toke.c"
yy115:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '\'':	goto yy117;
		case '=':	goto yy119;
		default:	goto yy116;
		}
yy116:
#line 74 "lib/Nana/toke.re"
		{ OP(TOKEN_LSHIFT); }
#line 533 "lib/Nana/toke.c"
yy117:
		++cursor;
#line 47 "lib/Nana/toke.re"
		{ OP(TOKEN_HEREDOC_SQ_START);  }
#line 538 "lib/Nana/toke.c"
yy119:
		++cursor;
#line 72 "lib/Nana/toke.re"
		{ OP(TOKEN_LSHIFT_ASSIGN); }
#line 543 "lib/Nana/toke.c"
yy121:
		++cursor;
#line 75 "lib/Nana/toke.re"
		{ OP(TOKEN_CMP); }
#line 548 "lib/Nana/toke.c"
yy123:
		++cursor;
#line 44 "lib/Nana/toke.re"
		{ OP(TOKEN_BYTES_DQ);  }
#line 553 "lib/Nana/toke.c"
yy125:
		++cursor;
#line 45 "lib/Nana/toke.re"
		{ OP(TOKEN_BYTES_SQ);  }
#line 558 "lib/Nana/toke.c"
yy127:
		++cursor;
#line 42 "lib/Nana/toke.re"
		{ OP(TOKEN_PLUS_ASSIGN);  }
#line 563 "lib/Nana/toke.c"
yy129:
		++cursor;
#line 41 "lib/Nana/toke.re"
		{ OP(TOKEN_PLUSPLUS); }
#line 568 "lib/Nana/toke.c"
	}
#line 110 "lib/Nana/toke.re"

    abort(); /* should not reach here */
}
