/* Generated by re2c 0.13.5 on Thu Apr 26 21:57:27 2012 */
#line 1 "lib/Nana/toke.re"
/* vim: set filetype=cpp: */
#include<stdio.h>
#include<stdlib.h>
#include "token.h"

/**
 * Take a token from string.
 *
 * @args src: source string.
 * @args len: length for 'src'.
 * @args output *used: used chars in src
 * @args output *found_end: make true if found __END__
 * @args output *lineno_inc: incremented line numbers.
 * @return int token id.
 */
int token_op(char *src, size_t len, int *used, int *found_end, int *lineno_inc) {
#define OP(type) do { *used+=(cursor-orig); return type; } while (0)
    *used = skip_ws(src, len, found_end, lineno_inc);
    if (*found_end) {
        return TOKEN_EOF;
    }
    if (*used == len) {
        return TOKEN_EOF;
    }
    char *cursor = src+*used;
    char *orig = cursor;
    char *marker = cursor;

    #line 41 "lib/Nana/toke.re"


    
#line 36 "lib/Nana/toke.c"
	{
		char yych;

		yych = (char)*cursor;
		switch (yych) {
		case '!':	goto yy24;
		case '"':	goto yy48;
		case '$':	goto yy42;
		case '%':	goto yy20;
		case '&':	goto yy34;
		case '\'':	goto yy50;
		case '(':	goto yy14;
		case '*':	goto yy44;
		case '+':	goto yy12;
		case ',':	goto yy22;
		case '-':	goto yy54;
		case '.':	goto yy30;
		case '/':	goto yy18;
		case '<':	goto yy16;
		case '=':	goto yy26;
		case '>':	goto yy36;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'd':
		case 'e':
		case 'g':
		case 'h':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 's':
		case 't':
		case 'v':
		case 'x':
		case 'y':
		case 'z':	goto yy9;
		case '[':	goto yy52;
		case '\\':	goto yy38;
		case '^':	goto yy28;
		case 'b':	goto yy10;
		case 'c':	goto yy2;
		case 'f':	goto yy8;
		case 'i':	goto yy6;
		case 'q':	goto yy11;
		case 'r':	goto yy4;
		case 'u':	goto yy5;
		case 'w':	goto yy7;
		case '{':	goto yy46;
		case '|':	goto yy32;
		case '~':	goto yy40;
		default:	goto yy56;
		}
yy2:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case 'l':	goto yy165;
		default:	goto yy129;
		}
yy3:
#line 51 "lib/Nana/toke.re"
		{ OP(TOKEN_IDENT); }
#line 128 "lib/Nana/toke.c"
yy4:
		yych = (char)*++cursor;
		switch (yych) {
		case 'e':	goto yy159;
		default:	goto yy129;
		}
yy5:
		yych = (char)*++cursor;
		switch (yych) {
		case 'n':	goto yy150;
		case 's':	goto yy151;
		default:	goto yy129;
		}
yy6:
		yych = (char)*++cursor;
		switch (yych) {
		case 'f':	goto yy148;
		default:	goto yy129;
		}
yy7:
		yych = (char)*++cursor;
		switch (yych) {
		case 'h':	goto yy143;
		default:	goto yy129;
		}
yy8:
		yych = (char)*++cursor;
		switch (yych) {
		case 'o':	goto yy140;
		default:	goto yy129;
		}
yy9:
		yych = (char)*++cursor;
		goto yy129;
yy10:
		yych = (char)*++cursor;
		switch (yych) {
		case '"':	goto yy136;
		case '\'':	goto yy138;
		default:	goto yy129;
		}
yy11:
		yych = (char)*++cursor;
		switch (yych) {
		case '!':
		case '"':
		case '\'':
		case '(':
		case '[':
		case '{':	goto yy123;
		case 'q':	goto yy127;
		case 'r':	goto yy126;
		case 'w':	goto yy125;
		default:	goto yy129;
		}
yy12:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '+':	goto yy121;
		case '=':	goto yy119;
		default:	goto yy13;
		}
yy13:
#line 54 "lib/Nana/toke.re"
		{ OP(TOKEN_PLUS);  }
#line 194 "lib/Nana/toke.c"
yy14:
		++cursor;
#line 57 "lib/Nana/toke.re"
		{ OP(TOKEN_LPAREN);  }
#line 199 "lib/Nana/toke.c"
yy16:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '<':	goto yy111;
		case '=':	goto yy109;
		default:	goto yy17;
		}
yy17:
#line 88 "lib/Nana/toke.re"
		{ OP(TOKEN_GT); }
#line 210 "lib/Nana/toke.c"
yy18:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy107;
		default:	goto yy19;
		}
yy19:
#line 60 "lib/Nana/toke.re"
		{ OP(TOKEN_DIV); }
#line 220 "lib/Nana/toke.c"
yy20:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy105;
		default:	goto yy21;
		}
yy21:
#line 62 "lib/Nana/toke.re"
		{ OP(TOKEN_MOD); }
#line 230 "lib/Nana/toke.c"
yy22:
		++cursor;
#line 63 "lib/Nana/toke.re"
		{ OP(TOKEN_COMMA); }
#line 235 "lib/Nana/toke.c"
yy24:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy103;
		case '~':	goto yy101;
		default:	goto yy25;
		}
yy25:
#line 66 "lib/Nana/toke.re"
		{ OP(TOKEN_NOT); }
#line 246 "lib/Nana/toke.c"
yy26:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy99;
		case '>':	goto yy97;
		case '~':	goto yy95;
		default:	goto yy27;
		}
yy27:
#line 70 "lib/Nana/toke.re"
		{ OP(TOKEN_ASSIGN); }
#line 258 "lib/Nana/toke.c"
yy28:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy93;
		default:	goto yy29;
		}
yy29:
#line 72 "lib/Nana/toke.re"
		{ OP(TOKEN_XOR); }
#line 268 "lib/Nana/toke.c"
yy30:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '.':	goto yy89;
		default:	goto yy31;
		}
yy31:
#line 75 "lib/Nana/toke.re"
		{ OP(TOKEN_DOT); }
#line 278 "lib/Nana/toke.c"
yy32:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy83;
		case '|':	goto yy85;
		default:	goto yy33;
		}
yy33:
#line 79 "lib/Nana/toke.re"
		{ OP(TOKEN_OR); }
#line 289 "lib/Nana/toke.c"
yy34:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '&':	goto yy81;
		case '=':	goto yy79;
		default:	goto yy35;
		}
yy35:
#line 82 "lib/Nana/toke.re"
		{ OP(TOKEN_AND); }
#line 300 "lib/Nana/toke.c"
yy36:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy73;
		case '>':	goto yy75;
		default:	goto yy37;
		}
yy37:
#line 92 "lib/Nana/toke.re"
		{ OP(TOKEN_LT); }
#line 311 "lib/Nana/toke.c"
yy38:
		++cursor;
#line 93 "lib/Nana/toke.re"
		{ OP(TOKEN_REF); }
#line 316 "lib/Nana/toke.c"
yy40:
		++cursor;
#line 94 "lib/Nana/toke.re"
		{ OP(TOKEN_TILDE); }
#line 321 "lib/Nana/toke.c"
yy42:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '{':	goto yy71;
		default:	goto yy43;
		}
yy43:
#line 119 "lib/Nana/toke.re"
		{ return TOKEN_EOF; }
#line 331 "lib/Nana/toke.c"
yy44:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '*':	goto yy67;
		case '=':	goto yy65;
		default:	goto yy45;
		}
yy45:
#line 99 "lib/Nana/toke.re"
		{ OP(TOKEN_MUL); }
#line 342 "lib/Nana/toke.c"
yy46:
		++cursor;
#line 103 "lib/Nana/toke.re"
		{ OP(TOKEN_LBRACE); }
#line 347 "lib/Nana/toke.c"
yy48:
		++cursor;
#line 111 "lib/Nana/toke.re"
		{ OP(TOKEN_STRING_DQ); }
#line 352 "lib/Nana/toke.c"
yy50:
		++cursor;
#line 112 "lib/Nana/toke.re"
		{ OP(TOKEN_STRING_SQ); }
#line 357 "lib/Nana/toke.c"
yy52:
		++cursor;
#line 113 "lib/Nana/toke.re"
		{ OP(TOKEN_LBRACKET); }
#line 362 "lib/Nana/toke.c"
yy54:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '-':	goto yy61;
		case '=':	goto yy57;
		case '>':	goto yy59;
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy63;
		default:	goto yy55;
		}
yy55:
#line 118 "lib/Nana/toke.re"
		{ OP(TOKEN_MINUS); }
#line 400 "lib/Nana/toke.c"
yy56:
		yych = (char)*++cursor;
		goto yy43;
yy57:
		++cursor;
#line 117 "lib/Nana/toke.re"
		{ OP(TOKEN_MINUS_ASSIGN); }
#line 408 "lib/Nana/toke.c"
yy59:
		++cursor;
#line 116 "lib/Nana/toke.re"
		{ OP(TOKEN_LAMBDA); }
#line 413 "lib/Nana/toke.c"
yy61:
		++cursor;
#line 115 "lib/Nana/toke.re"
		{ OP(TOKEN_MINUSMINUS); }
#line 418 "lib/Nana/toke.c"
yy63:
		++cursor;
#line 114 "lib/Nana/toke.re"
		{ OP(TOKEN_FILETEST); }
#line 423 "lib/Nana/toke.c"
yy65:
		++cursor;
#line 98 "lib/Nana/toke.re"
		{ OP(TOKEN_MUL_ASSIGN); }
#line 428 "lib/Nana/toke.c"
yy67:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy69;
		default:	goto yy68;
		}
yy68:
#line 97 "lib/Nana/toke.re"
		{ OP(TOKEN_POW); }
#line 438 "lib/Nana/toke.c"
yy69:
		++cursor;
#line 96 "lib/Nana/toke.re"
		{ OP(TOKEN_POW_ASSIGN); }
#line 443 "lib/Nana/toke.c"
yy71:
		++cursor;
#line 95 "lib/Nana/toke.re"
		{ OP(TOKEN_DEREF); }
#line 448 "lib/Nana/toke.c"
yy73:
		++cursor;
#line 91 "lib/Nana/toke.re"
		{ OP(TOKEN_LE); }
#line 453 "lib/Nana/toke.c"
yy75:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy77;
		default:	goto yy76;
		}
yy76:
#line 90 "lib/Nana/toke.re"
		{ OP(TOKEN_RSHIFT); }
#line 463 "lib/Nana/toke.c"
yy77:
		++cursor;
#line 89 "lib/Nana/toke.re"
		{ OP(TOKEN_RSHIFT_ASSIGN); }
#line 468 "lib/Nana/toke.c"
yy79:
		++cursor;
#line 81 "lib/Nana/toke.re"
		{ OP(TOKEN_AND_ASSIGN); }
#line 473 "lib/Nana/toke.c"
yy81:
		++cursor;
#line 80 "lib/Nana/toke.re"
		{ OP(TOKEN_ANDAND); }
#line 478 "lib/Nana/toke.c"
yy83:
		++cursor;
#line 78 "lib/Nana/toke.re"
		{ OP(TOKEN_OR_ASSIGN); }
#line 483 "lib/Nana/toke.c"
yy85:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '=':	goto yy87;
		default:	goto yy86;
		}
yy86:
#line 77 "lib/Nana/toke.re"
		{ OP(TOKEN_OROR); }
#line 493 "lib/Nana/toke.c"
yy87:
		++cursor;
#line 76 "lib/Nana/toke.re"
		{ OP(TOKEN_OROR_ASSIGN); }
#line 498 "lib/Nana/toke.c"
yy89:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '.':	goto yy91;
		default:	goto yy90;
		}
yy90:
#line 74 "lib/Nana/toke.re"
		{ OP(TOKEN_DOTDOT); }
#line 508 "lib/Nana/toke.c"
yy91:
		++cursor;
#line 73 "lib/Nana/toke.re"
		{ OP(TOKEN_DOTDOTDOT); }
#line 513 "lib/Nana/toke.c"
yy93:
		++cursor;
#line 71 "lib/Nana/toke.re"
		{ OP(TOKEN_XOR_ASSIGN); }
#line 518 "lib/Nana/toke.c"
yy95:
		++cursor;
#line 69 "lib/Nana/toke.re"
		{ OP(TOKEN_REGEXP_MATCH); }
#line 523 "lib/Nana/toke.c"
yy97:
		++cursor;
#line 68 "lib/Nana/toke.re"
		{ OP(TOKEN_FAT_COMMA); }
#line 528 "lib/Nana/toke.c"
yy99:
		++cursor;
#line 67 "lib/Nana/toke.re"
		{ OP(TOKEN_EQUAL_EQUAL); }
#line 533 "lib/Nana/toke.c"
yy101:
		++cursor;
#line 65 "lib/Nana/toke.re"
		{ OP(TOKEN_REGEXP_NOT_MATCH); }
#line 538 "lib/Nana/toke.c"
yy103:
		++cursor;
#line 64 "lib/Nana/toke.re"
		{ OP(TOKEN_NOT_EQUAL); }
#line 543 "lib/Nana/toke.c"
yy105:
		++cursor;
#line 61 "lib/Nana/toke.re"
		{ OP(TOKEN_MOD_ASSIGN); }
#line 548 "lib/Nana/toke.c"
yy107:
		++cursor;
#line 59 "lib/Nana/toke.re"
		{ OP(TOKEN_DIV_ASSIGN); }
#line 553 "lib/Nana/toke.c"
yy109:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '>':	goto yy117;
		default:	goto yy110;
		}
yy110:
#line 87 "lib/Nana/toke.re"
		{ OP(TOKEN_GE); }
#line 563 "lib/Nana/toke.c"
yy111:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '\'':	goto yy113;
		case '=':	goto yy115;
		default:	goto yy112;
		}
yy112:
#line 85 "lib/Nana/toke.re"
		{ OP(TOKEN_LSHIFT); }
#line 574 "lib/Nana/toke.c"
yy113:
		++cursor;
#line 58 "lib/Nana/toke.re"
		{ OP(TOKEN_HEREDOC_SQ_START);  }
#line 579 "lib/Nana/toke.c"
yy115:
		++cursor;
#line 83 "lib/Nana/toke.re"
		{ OP(TOKEN_LSHIFT_ASSIGN); }
#line 584 "lib/Nana/toke.c"
yy117:
		++cursor;
#line 86 "lib/Nana/toke.re"
		{ OP(TOKEN_CMP); }
#line 589 "lib/Nana/toke.c"
yy119:
		++cursor;
#line 53 "lib/Nana/toke.re"
		{ OP(TOKEN_PLUS_ASSIGN);  }
#line 594 "lib/Nana/toke.c"
yy121:
		++cursor;
#line 52 "lib/Nana/toke.re"
		{ OP(TOKEN_PLUSPLUS); }
#line 599 "lib/Nana/toke.c"
yy123:
		++cursor;
#line 110 "lib/Nana/toke.re"
		{ OP(TOKEN_STRING_Q_START); }
#line 604 "lib/Nana/toke.c"
yy125:
		yych = (char)*++cursor;
		switch (yych) {
		case '!':
		case '"':
		case '\'':
		case '(':
		case '[':
		case '{':	goto yy134;
		default:	goto yy129;
		}
yy126:
		yych = (char)*++cursor;
		switch (yych) {
		case '!':
		case '"':
		case '\'':
		case '(':
		case '[':
		case '{':	goto yy132;
		default:	goto yy129;
		}
yy127:
		yych = (char)*++cursor;
		switch (yych) {
		case '!':
		case '"':
		case '\'':
		case '(':
		case '[':
		case '{':	goto yy130;
		default:	goto yy129;
		}
yy128:
		++cursor;
		yych = (char)*cursor;
yy129:
		switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy128;
		default:	goto yy3;
		}
yy130:
		++cursor;
#line 107 "lib/Nana/toke.re"
		{ OP(TOKEN_STRING_QQ_START); }
#line 712 "lib/Nana/toke.c"
yy132:
		++cursor;
#line 108 "lib/Nana/toke.re"
		{ OP(TOKEN_REGEXP_QR_START); }
#line 717 "lib/Nana/toke.c"
yy134:
		++cursor;
#line 109 "lib/Nana/toke.re"
		{ OP(TOKEN_QW_START); }
#line 722 "lib/Nana/toke.c"
yy136:
		++cursor;
#line 55 "lib/Nana/toke.re"
		{ OP(TOKEN_BYTES_DQ);  }
#line 727 "lib/Nana/toke.c"
yy138:
		++cursor;
#line 56 "lib/Nana/toke.re"
		{ OP(TOKEN_BYTES_SQ);  }
#line 732 "lib/Nana/toke.c"
yy140:
		yych = (char)*++cursor;
		switch (yych) {
		case 'r':	goto yy141;
		default:	goto yy129;
		}
yy141:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy128;
		default:	goto yy142;
		}
yy142:
#line 50 "lib/Nana/toke.re"
		{ OP(TOKEN_FOR); }
#line 810 "lib/Nana/toke.c"
yy143:
		yych = (char)*++cursor;
		switch (yych) {
		case 'i':	goto yy144;
		default:	goto yy129;
		}
yy144:
		yych = (char)*++cursor;
		switch (yych) {
		case 'l':	goto yy145;
		default:	goto yy129;
		}
yy145:
		yych = (char)*++cursor;
		switch (yych) {
		case 'e':	goto yy146;
		default:	goto yy129;
		}
yy146:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy128;
		default:	goto yy147;
		}
yy147:
#line 49 "lib/Nana/toke.re"
		{ OP(TOKEN_WHILE); }
#line 900 "lib/Nana/toke.c"
yy148:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy128;
		default:	goto yy149;
		}
yy149:
#line 48 "lib/Nana/toke.re"
		{ OP(TOKEN_IF); }
#line 972 "lib/Nana/toke.c"
yy150:
		yych = (char)*++cursor;
		switch (yych) {
		case 'l':	goto yy154;
		default:	goto yy129;
		}
yy151:
		yych = (char)*++cursor;
		switch (yych) {
		case 'e':	goto yy152;
		default:	goto yy129;
		}
yy152:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy128;
		default:	goto yy153;
		}
yy153:
#line 46 "lib/Nana/toke.re"
		{ OP(TOKEN_USE); }
#line 1056 "lib/Nana/toke.c"
yy154:
		yych = (char)*++cursor;
		switch (yych) {
		case 'e':	goto yy155;
		default:	goto yy129;
		}
yy155:
		yych = (char)*++cursor;
		switch (yych) {
		case 's':	goto yy156;
		default:	goto yy129;
		}
yy156:
		yych = (char)*++cursor;
		switch (yych) {
		case 's':	goto yy157;
		default:	goto yy129;
		}
yy157:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy128;
		default:	goto yy158;
		}
yy158:
#line 47 "lib/Nana/toke.re"
		{ OP(TOKEN_UNLESS); }
#line 1146 "lib/Nana/toke.c"
yy159:
		yych = (char)*++cursor;
		switch (yych) {
		case 't':	goto yy160;
		default:	goto yy129;
		}
yy160:
		yych = (char)*++cursor;
		switch (yych) {
		case 'u':	goto yy161;
		default:	goto yy129;
		}
yy161:
		yych = (char)*++cursor;
		switch (yych) {
		case 'r':	goto yy162;
		default:	goto yy129;
		}
yy162:
		yych = (char)*++cursor;
		switch (yych) {
		case 'n':	goto yy163;
		default:	goto yy129;
		}
yy163:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy128;
		default:	goto yy164;
		}
yy164:
#line 45 "lib/Nana/toke.re"
		{ OP(TOKEN_RETURN); }
#line 1242 "lib/Nana/toke.c"
yy165:
		yych = (char)*++cursor;
		switch (yych) {
		case 'a':	goto yy166;
		default:	goto yy129;
		}
yy166:
		yych = (char)*++cursor;
		switch (yych) {
		case 's':	goto yy167;
		default:	goto yy129;
		}
yy167:
		yych = (char)*++cursor;
		switch (yych) {
		case 's':	goto yy168;
		default:	goto yy129;
		}
yy168:
		++cursor;
		switch ((yych = (char)*cursor)) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z':	goto yy128;
		default:	goto yy169;
		}
yy169:
#line 44 "lib/Nana/toke.re"
		{ OP(TOKEN_CLASS);  }
#line 1332 "lib/Nana/toke.c"
	}
#line 121 "lib/Nana/toke.re"

    abort(); /* should not reach here */
}
